// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD_hdiQL2j-bu62a38nkz2tpCJ2TRN04A',
    appId: '1:662026099182:web:1208471c4821b34f81d6ff',
    messagingSenderId: '662026099182',
    projectId: 'time-register-f68a8',
    authDomain: 'time-register-f68a8.firebaseapp.com',
    storageBucket: 'time-register-f68a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZPZg1Wxb7tKY5m2k0P0Ug-tz6ArwAjuM',
    appId: '1:662026099182:android:bb4421d5d5a7a79581d6ff',
    messagingSenderId: '662026099182',
    projectId: 'time-register-f68a8',
    storageBucket: 'time-register-f68a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGIHGnfdWgDUCxgMFYxytTDGZots5aH0g',
    appId: '1:662026099182:ios:526c20377160ebe581d6ff',
    messagingSenderId: '662026099182',
    projectId: 'time-register-f68a8',
    storageBucket: 'time-register-f68a8.firebasestorage.app',
    iosBundleId: 'com.example.timeRegisterFlutter',
  );
}
